FROM node:20-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install --omit=optional
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/vite.config.js ./

EXPOSE 4173
CMD ["npm", "run", "preview"]
